name: Deploy to Shopify

on:
  push:
    branches:
      - checkout-ui

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/app
      
    - name: Install dependencies
      run: npm install

    - name: Deploy to Shopify
      env:
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_API_SECRET: ${{ secretsSHOPIFY_API_SECRET }}
        SHOPIFY_APP_URL: ${{ secrets.SHOPIFY_APP_URL }}
        # Add any other environment variables your deploy command needs
      run: npm run shopify app deploy
